name: two jobs

on:
  push:
    branches:
       - feature_new

jobs:
        JobLinux:
                name: Job Linux
                runs-on: ubuntu-latest
                steps:
                        - name: Etapa 01
                          uses: actions/checkout@v4
                        - name: Etapa 02
                          run: |
                                  echo "$(cat README.md)"
                                  uname -a
        JobWindows:
                name: Job Windows
                runs-on: windows-latest
                steps:
                        - name: Etapa 01
                          uses: actions/checkout@v4
                        - name: Etapa 02
                          run: "Get-CimInstance Win32_OperatingSystem"
